Display checkbox values when not selected
gravityflow/gravityflow pull request #342
Opened 2020-07-24 20:13 UTC by saifsultanc

## Description
Resonating with [this](https://gravityflow.productboard.com/feature-board/1199966-feature-organization/features/3835948/insights) ProductBoard feature request, this update displays all of the checkbox values on the entry detail page. Any of the checkbox values that are not selected by the user are displayed with a strike over them.

## Testing instructions

- Create a form with different checkbox fields.
- Add a Workflow Approval Step.
- After submitting a form entry, check the updated behaviour on the Workflow

## Automated Test Enhancements
N/A

## Screenshots
N/A

## Documentation Changes?
N/A

## Checklist:
- [x] I've tested the code.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code follows the inline documentation standards.

2020-07-25 12:01 UTC, richardW8k commented on includes/pages/class-entry-detail.php
> +						if ( $field['type'] == 'checkbox' && $display_value == '&nbsp;') {
We should use object notation when interacting with the field. This also limits the scope of this change to the Checkbox field. How about using `$field->get_input_type() == 'checkbox'` so checkbox type pricing and post fields also supported?

2020-07-25 12:02 UTC, richardW8k commented on includes/pages/class-entry-detail.php
> +						if ( $field['type'] == 'checkbox' ) {
See first comment.

2020-07-25 12:05 UTC, richardW8k commented on includes/pages/class-entry-detail.php
> +							$all_html_values = $field->get_checkbox_choices();
This triggers a fatal error:

```
[25-Jul-2020 11:56:40 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function GF_Field_Checkbox::get_checkbox_choices(), 0 passed in /Users/richard/LocalBetaSites/gravity-flow/app/public/wp-content/plugins/gravityflow/includes/pages/class-entry-detail.php on line 961 and at least 2 expected in /Users/richard/LocalBetaSites/gravity-flow/app/public/wp-content/plugins/gravityforms/includes/fields/class-gf-field-checkbox.php:510
Stack trace:
#0 /Users/richard/LocalBetaSites/gravity-flow/app/public/wp-content/plugins/gravityflow/includes/pages/class-entry-detail.php(961): GF_Field_Checkbox->get_checkbox_choices()
#1 /Users/richard/LocalBetaSites/gravity-flow/app/public/wp-content/plugins/gravityflow/includes/pages/class-entry-detail.php(738): Gravity_Flow_Entry_Detail::fields(Array, Array, false, Object(Gravity_Flow_Step_Approval), 'table')
#2 /Users/richard/LocalBetaSites/gravity-flow/app/public/wp-content/plugins/gravityflow/includes/pages/class-entry-detail.php(115): Gravity_Flow_Entry_Detail::entry_detail_grid(Array, Array, true in /Users/richard/LocalBetaSites/gravity-flow/app/public/wp-content/plugins/gravityforms/includes/fields/class-gf-field-checkbox.php on line 510
```

Also, if the fatal error hadn't occurred would using this method result in the "select all" choice being output when that feature is enabled on the field?

2020-07-25 12:09 UTC, richardW8k commented on includes/pages/class-entry-detail.php
> +							$all_li = $dom->getElementsByTagName( 'li' );
This probably won't work with forms using the new markup with Gravity Forms 2.5 as that uses div elements for most fields instead of list elements.

2020-07-25 12:11 UTC, richardW8k commented on includes/pages/class-entry-detail.php
> +									$content .= '<li><strike>' . $unselected_value . '</strike></li>';
The [strike element is obsolete](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strike) so we should use a different approach here.

2020-09-15 20:39 UTC, saifsultanc commented on includes/pages/class-entry-detail.php
> +							$all_li = $dom->getElementsByTagName( 'li' );
This displayed fine with GF 2.5-beta-1.7.

2020-09-19 19:21 UTC, richardW8k requested changes
The fatal error is resolved but both the selected choice and the choice for the select all feature are also listed:

<img width="170" alt="Screenshot 2020-09-19 at 20 11 18" src="https://user-images.githubusercontent.com/1872371/93687300-a6570700-fab4-11ea-8088-40daf014addd.png">

My test field has values enabled:

<img width="510" alt="Screenshot 2020-09-19 at 20 14 56" src="https://user-images.githubusercontent.com/1872371/93687324-cedf0100-fab4-11ea-8fe2-db3cdc00d594.png">

Since values are enabled shouldn't it list the choice values instead of the choice text?

2021-01-30 18:15 UTC, richardW8k requested changes
The select all and choice text/value issues are resolved. There are a few code formatting issues to resolve.

2021-01-30 18:15 UTC, richardW8k commented on includes/pages/class-entry-detail.php
> +						if ( $field->get_input_type() == 'checkbox' && $display_value == '&nbsp;') {
needs a space between `')`

2021-01-30 18:15 UTC, richardW8k commented on includes/pages/class-entry-detail.php
> +																	</tr>';
can the indent here be reduced?

2021-01-30 18:15 UTC, richardW8k commented on includes/pages/class-entry-detail.php
> +						else {
i would usually place this on the same line as the closing braket

2021-01-30 18:15 UTC, richardW8k commented on includes/pages/class-entry-detail.php
> +																	</tr>';
can this indent be reduced?

2021-01-30 18:15 UTC, richardW8k commented on includes/pages/class-entry-detail.php
> +							$dom = new DOMDocument();
alignment

2021-01-30 18:15 UTC, richardW8k commented on includes/pages/class-entry-detail.php
> +										if( is_object( $value_object ) ) {
missing spaces between the `if(`'s

2021-01-30 18:15 UTC, richardW8k commented on includes/pages/class-entry-detail.php
> +							$selected_values = array();
alignment

2021-01-30 18:26 UTC, saifsultanc commented
Fixed formatting. Re-requesting review.

2021-01-31 14:58 UTC, closed without merging

2021-01-31 14:59 UTC, stevehenty commented
Closed to see if we get more feedback about the way checkboxes are handled.

2021-01-31 15:00 UTC, saifsultanc commented
As discussed with Steve, we are not going ahead with the DOMDocument approach for now. It's tendency to be fragile, esp considering the difference in how Gravity Forms handles it. Potentially breaking other use cases.

Will reopen later, depending on more elaborate feedback.