Added filter to remove inbox count
gravityflow/gravityflow pull request #354
Opened 2020-09-10 18:22 UTC by saifsultanc

## Description
Re: [HS#14662](https://secure.helpscout.net/conversation/1274562929/14662/) to remove inbox count red bubble.

## Testing instructions
- After switching to this branch, add the filter call on functions.php:
`add_filter( 'gravityflow_show_inbox_count', '__return_false', 1 );`
- Refresh Wordpress Dashboard and confirm the filter count is no longer.
- Remove the filter call from functions.php, and check to see the inbox count value is back.

## Automated Test Enhancements
N/A
 
## Screenshots
N/A

## Documentation Changes?
Add documentation for the filter `gravityflow_show_inbox_count`

`add_filter( 'gravityflow_show_inbox_count', '__return_false', 1 );`

Alternativey,
```
add_filter( 'gravityflow_show_inbox_count', 'sh_gravityflow_show_inbox_count', 10, 1 );
function sh_gravityflow_show_inbox_count( $show ) {
	return false;
}
```

## Checklist:
- [x] I've tested the code.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code follows the inline documentation standards.

2020-09-10 19:49 UTC, Idealien requested changes
Functionality is sound.
I'd recommend the filter be renamed to gravityflow_inbox_count_display to be consistent with the [naming conventions](https://github.com/gravityflow/gravityflow/wiki/Naming-conventions-for-hooks) to give an emphasis to the object being filtered, followed by when it is going to fire.

2020-09-12 13:36 UTC, richardW8k requested changes

2020-09-12 13:36 UTC, richardW8k commented on class-gravity-flow.php
> +			if ( isset( $show ) && ! $show ) {
We don't usually use an approach like this when adding filters. Normally the argument would be defaulted to `true` or `false` e.g.

```suggestion
			$show = apply_filters( 'gravityflow_inbox_count_display', true );
			if ( ! $show ) {
```

There should also be a docblock with since and param tags.

2020-09-15 12:48 UTC, richardW8k approved these changes

2020-09-15 14:13 UTC, merged