Fix token submission UI step
gravityflow/gravityflow pull request #371
Opened 2020-12-07 20:06 UTC by saifsultanc

## Description
Re: [HS# 15628](https://secure.helpscout.net/conversation/1356724153/15628?folderId=3509661)
Following [PR#359](https://github.com/gravityflow/gravityflow/pull/359), a scenario was presented which caused issues with that update. We look at adding an argument to process the entry detail, instead of disabling the $step.

## Testing instructions
1. Create a form with 2 fields (say Field A and Field B). Also add an email field.
2. Create a User Input workflow step, with Field A as the editable field and the only display field. Assign this step to the Email field. Pass `{workflow_entry_link}` merge tag on the assignee email.
3. Process an entry for the form. Enter values for both fields A and B. Also, enter your email id in the email field.
4. Open the tokenized workflow entry link received in your email. Click Submit.
5. After submission, the workflow will display 'Entry updated and marked complete'. However, it will display both fields A and B. In Step 2, we had set Field A as the only display field.
6. Now switch to this branch, and repeat steps 1 to 5. Notice, the workflow only displays field A after submission.

## Automated Test Enhancements
N/A
 
## Screenshots
N/A

## Documentation Changes?
N/A

## Checklist:
- [x] I've tested the code.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code follows the inline documentation standards.

2020-12-13 23:12 UTC, Idealien commented
I believe Step 5 in test instructions is working as expected in the master branch. Determination of which fields are displayed when a non-current-assignee accesses an entry is taken from the complete step settings.

With the PR branch, I encounter the following notice on several inbox/status views of the entry detail whether as assignee or not:
Notice: Undefined index: disable_workflow_update in ....gravityflow\includes\pages\class-entry-detail.php on line 46

The related issue I was describing earlier this week that occurs in 2.6 (related to assignee - either user or email token - completing a approval/user input step continuing to see the approval/submit buttons) is no longer exhibiting in master branch.

2020-12-13 23:13 UTC, Idealien commented
@saifsultanc - Please correct me if I'm wrong, but based on the comments above, might this PR no longer be required?
If you feel it is, please provide updated instructions related to step 5 w.r.t complete step settings and address the notice error.

2020-12-13 23:14 UTC, Idealien requested changes
@saifsultanc  - Please correct me if I'm wrong, but based on the comments above, might this PR no longer be required? If you feel it is, please provide updated instructions related to step 5 w.r.t complete step settings and address the notice error.

2020-12-16 02:26 UTC, saifsultanc commented
> I believe Step 5 in test instructions is working as expected in the master branch. Determination of which fields are displayed when a non-current-assignee accesses an entry is taken from the complete step settings.

Step 5 working as expected? Can you please confirm you mean that the non-display fields are not displayed on that workflow step. I assume that's the expected behaviour. 

With the master, as I mentioned, the non-display fields on the workflow step did appear (after submission).

2021-01-03 18:57 UTC, Idealien commented
Discussed with Saif that this PR can be closed - the affected setup did not have either a Start or Complete step which is how the non-assignee displayed fields are meant to be controlled.

2021-01-03 18:57 UTC, closed without merging