Fix Order Summary always displaying with Complete Step Settings
gravityflow/gravityflow pull request #391
Opened 2021-03-23 07:14 UTC by saifsultanc

## Description
Addresses [Issue #86](https://github.com/gravityflow/backlog/issues/86)
Order Summary always displays at end of Workflow, regardless of whether it is enabled or disabled on the Complete Step Settings.

## Testing instructions
1. Create a form with Pricing Fields.
2. Add a few workflow steps (like Approval, User Input, etc).
3. Edit Complete Step settings to disable Order Summary.
4. Process the form and workflow, at the end of the workflow the Order Summary would still be displayed.
5. Now switch to this branch, repeat step 4 and now Order Summary will not be displayed.
6. Update workflow to enable Order Summary on Complete Step and repeat step 4 again. Now Order Summary will display, as expected.

## Automated Test Enhancements
N/A
 
## Screenshots
N/A

## Documentation Changes
N/A

## Checklist:
- [x] I've tested the code.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code follows the inline documentation standards.

2021-03-25 01:48 UTC, Idealien requested changes

2021-03-25 01:48 UTC, Idealien commented on includes/pages/class-entry-detail.php
> +			$current_step = $complete_step;
While this approach is functional, it modifies $current_step in addition to determining the value of $summary_enabled. Please put the additional check of feed/setting inside an else/if block so that current / complete are evaluated separately. It reduces risk that future enhancements evaluating step do not get the expected value.

2021-03-25 01:50 UTC, Idealien commented on includes/pages/class-entry-detail.php
> +			$current_step = $complete_step;
We should also check whether existing acceptance test(s) validate this setting or could be enhanced to as a part of this PR.

2021-03-25 06:33 UTC, saifsultanc commented on includes/pages/class-entry-detail.php
> +			$current_step = $complete_step;
@Idealien : I had initially done it that way, but to avoid code duplication/repeated logic went for a workaround like this. Would it make sense to use a different variable like `$processing_step`, and then use it as :

$complete_step = gravity_flow()->get_workflow_complete_step( $form['id'] );
$processing_step = ( ! $current_step && $complete_step ) ? $complete_step : $current_step;

and now proceed with the rest of the logic on `$processing_step`?

2021-03-26 01:00 UTC, Idealien commented on includes/pages/class-entry-detail.php
> +			$current_step = $complete_step;
Good idea, yes.

2021-03-29 22:57 UTC, Idealien approved these changes

2021-03-30 15:33 UTC, merged