Add CSS Classes to the Workflow Status Box
gravityflow/gravityflow pull request #414
Opened 2021-06-11 20:08 UTC by saifsultanc

## Description
The Workflow Status Box is built with text and line breaks. This makes it difficult for customers to tap specific items on the markup for customizations (CSS rules for instance). This PR adds custom classes to make the customizations easy.

This resolves [gravityflow/backlog#100](https://github.com/gravityflow/backlog/issues/100).

## Testing instructions
1. After switching this PR, add CSS rules to different elements on the Workflow Status Box.
2. Confirm the CSS customizations works fine.
3. Repeat to check with Gravity Forms 2.4 as well.

## Automated Test Enhancements
N/A
 
## Screenshots
N/A

## Documentation Changes
N/A

## Checklist:
- [x] I've tested the code.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code follows the inline documentation standards.

2021-06-12 16:26 UTC, Idealien commented on class-gravity-flow.php
> +			printf( '<div class="gravityflow-status-box-field gravityflow-status-box-field-entry-id">%s: %s</div>', esc_html__( 'Entry ID', 'gravityflow' ), $entry_id_link );
One comment that could apply for each row of data output would be to ensure the label / value %s each get wrapped in a <span> with a class. WIthout, it's hard to style (or hide) each separately.

printf( '<div class="gravityflow-status-box-field gravityflow-status-box-field-entry-id"><span class="gravityflow-status-box-field-label">%s: </span><span>gravityflow-status-box-field-value">%s</span></div>', esc_html__( 'Entry ID', 'gravityflow' ), $entry_id_link );

2021-06-12 16:32 UTC, Idealien requested changes

2021-06-12 16:32 UTC, Idealien commented on class-gravity-flow.php
> +					esc_html_e( '<div class="gravityflow-status-box-field gravityflow-status-box-field-last-updated">Last updated</div>', 'gravityflow' ); ?>: <?php echo esc_html( $last_updated );
Format through printf so that the 'Last updated' string does not include extraneous translation markup.

2021-06-12 16:32 UTC, Idealien commented on class-gravity-flow.php
> +			printf( '<div class="gravityflow-status-box-field gravityflow-status-box-field-entry-id">%s: %s</div>', esc_html__( 'Entry ID', 'gravityflow' ), $entry_id_link );
One comment that could apply for each row of data output would be to ensure the label / value %s each get wrapped in a <span> with a class. WIthout, it's hard to style (or hide) each separately.

`printf( '<div class="gravityflow-status-box-field gravityflow-status-box-field-entry-id"><span class="gravityflow-status-box-field-label">%s: </span><span>gravityflow-status-box-field-value">%s</span></div>', esc_html__( 'Entry ID', 'gravityflow' ), $entry_id_link );`

2021-06-12 16:37 UTC, Idealien commented on class-gravity-flow.php
> +					esc_html_e( '<div class="gravityflow-status-box-field gravityflow-status-box-field-last-updated">Last updated</div>', 'gravityflow' ); ?>: <?php echo esc_html( $last_updated );
![image](https://user-images.githubusercontent.com/4549984/121783125-f4e48e00-cb7a-11eb-9776-a63b2e5cc6cd.png)

2021-06-19 16:59 UTC, Idealien requested changes
The changes applied are great and address all of markup generated in maybe_display_entry_detail_workflow_info function. What do you think about adding similar to the maybe_display_entry_detail_step_status function? It also generates markup within the #minor-publising/.gravityflow-status-box. for the elements of 
- step name
- scheduled/expired 
- workflow detail box

![image](https://user-images.githubusercontent.com/4549984/122649876-0a6b3200-d0fe-11eb-9003-bd0013624a85.png)

2021-07-30 01:55 UTC, Idealien requested changes

2021-07-30 01:55 UTC, Idealien commented on includes/steps/class-step-approval.php
>  			<div>
**Looking good!**

This container (of assignees), and the 'gravityflow-note', are the only two that are now missing a named container. Can it be added and check if any CSS (margins/padding) can be cleaned up since the gravityflow-status-box-field selector has a consistent amount?

2021-08-04 03:44 UTC, Idealien approved these changes
I added a few items relating to consistency between approval and user input step types. Removing some line breaks that can now better be handled via the CSS classes.

Marking PR as approved - Saif could you make 2 minor revisions before you merge please.
1) Either update change_log.txt or add to the PR description with some more details about the classes added. Will help for the release notes to highlight what people can now expect to use.

2) A small alignment difference remains on the user input step in the new branch.
![image](https://user-images.githubusercontent.com/4549984/128118708-3f4597a0-35ba-4dee-91a0-dd38b676ac56.png)

2021-08-04 07:29 UTC, saifsultanc commented
> I added a few items relating to consistency between approval and user input step types. Removing some line breaks that can now better be handled via the CSS classes.
> 
> Marking PR as approved - Saif could you make 2 minor revisions before you merge please.
> 
> 1. Either update change_log.txt or add to the PR description with some more details about the classes added. Will help for the release notes to highlight what people can now expect to use.
> 2. A small alignment difference remains on the assignees of user input step in the new branch.
>    ![image](https://user-images.githubusercontent.com/4549984/128118708-3f4597a0-35ba-4dee-91a0-dd38b676ac56.png)

1. Updated the PR description
2. Fixed the alignment. Both Approval and User Input step alignments match now.

2021-08-04 07:30 UTC, merged